<?php

namespace Dav\CooptBundle\Repository;

/**
 * CooptationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CooptationRepository extends \Doctrine\ORM\EntityRepository
{
}
